### ISSUE TITLE
Problems with singularity

### ISSUE THREAD

**Issue by yilevine** [drneavin/Demultiplexing_Doublet_Detecting_Docs#10]
Hi Drew,

Thanks for the Demuxafy tool. It is very useful!

I was running DoubletDetection on the test data with singularity image, but it always gave me an error. 

> INFO:    Converting SIF file to temporary sandbox...
Traceback (most recent call last):
  File "/opt/Demultiplexing_Doublet_Detecting_Docs/scripts/DoubletDetection.py", line 29, in <module>
    import doubletdetection
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/doubletdetection/__init__.py", line 1, in <module>
    from .doubletdetection import BoostClassifier
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/doubletdetection/doubletdetection.py", line 11, in <module>
    import scanpy as sc
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/scanpy/__init__.py", line 14, in <module>
    from . import tools as tl
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/scanpy/tools/__init__.py", line 1, in <module>
    from ..preprocessing import pca
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/scanpy/preprocessing/__init__.py", line 1, in <module>
    from ._recipes import recipe_zheng17, recipe_weinreb17, recipe_seurat
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/scanpy/preprocessing/_recipes.py", line 8, in <module>
    from ._deprecated.highly_variable_genes import (
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/scanpy/preprocessing/_deprecated/highly_variable_genes.py", line 11, in <module>
    from .._utils import _get_mean_var
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/scanpy/preprocessing/_utils.py", line 45, in <module>
    @numba.njit(cache=True)
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/numba/core/decorators.py", line 212, in wrapper
    disp.enable_caching()
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/numba/core/dispatcher.py", line 863, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/numba/core/caching.py", line 601, in __init__
    self._impl = self._impl_class(py_func)
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/numba/core/caching.py", line 338, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function 'sparse_mean_var_minor_axis': no locator available for file '/opt/conda/envs/py37/lib/python3.7/site-packages/scanpy/preprocessing/_utils.py'

The code I used was
`singularity exec --bind $SINGULARITY/testing $SINGULARITY/Demuxafy.sif DoubletDetection.py -m $COUNTS -o $DOUBLETDETECTION_OUTDIR
`
I also tried other tools like Scrublet in the image. I got the same error as well.

Do you have any idea?

Thanks
Yile

**Comment by drneavin** [comment]
Hi @yilevine ,

I apologize, as I just realize that you posted this a while ago and I must have missed it. I have never experienced this error before. To start to try to work this out, can you confirm:
- What version of the singularity image you're using (`singularity inspect $SIF)?
- the paths that are provided for `$COUNTS` and `$DOUBLETDETECTION_OUTDIR` relative to the path `$SINGULARITY`?

Cheers,
Drew

**Comment by drneavin** [comment]
Closing due to inactivity, please reopen if this issue still exists
