### ISSUE TITLE
Numpy incompatibility issue when running Demuxalot

### ISSUE THREAD

**Issue by ziyuan-ma** [drneavin/Demultiplexing_Doublet_Detecting_Docs#57]
Thank you for providing such a useful package! I am currently using version `v3.0.0` of Demuxafy on an HPC cluster, but I encountered the following error message while running the `Demuxalot.py` script:

```
Traceback (most recent call last):
  File "/opt/Demultiplexing_Doublet_Detecting_Docs/scripts/Demuxalot.py", line 4, in <module>
    import demuxalot
  File "/miniconda3/lib/python3.9/site-packages/demuxalot/__init__.py", line 3, in <module>
    from .utils import BarcodeHandler
  File "/miniconda3/lib/python3.9/site-packages/demuxalot/utils.py", line 7, in <module>
    import pandas as pd
  File "/miniconda3/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/miniconda3/lib/python3.9/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/miniconda3/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/miniconda3/lib/python3.9/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/miniconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/miniconda3/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Could this issue be related to a built-in `numpy` incompatibility? I would appreciate any insights or recommendations on how to resolve this. Thank you!

**Comment by giray-jax** [comment]
I am having the exact same issue!
